package:
  name: hamframe
  version: "0.1"

build:
  number: 0
  script: python setup.py install # If using setup.py

source:
  git_rev:
  git_url:

requirements:
  build:
    - python
    - setuptools # If using setup.py
  run:
    - python

test:
  imports:
    -

about:
  home: https://github.com/ckuhtz/hamframe
  license: MIT
  license_family: MIT
  summary: Framework for Ham Radio
  author: Christian Kuhtz
  license_file: LICENSE

extra:
  recipe-maintainers:
    - ckuhtz
