name: api

on:
  push:
    branches: [ "main" ]
    paths:
      - 'api/**/*.py'
      - 'api/**/*.sh'
      - 'api/**/Dockerfile'
      - 'api/**/requirements.txt'
      - '**/api.yml'
  pull_request:
    branches: [ "main" ]
    paths:
      - 'api/**/*.py'
      - 'api/**/*.sh'
      - 'api/**/Dockerfile'
      - 'api/**/requirements.txt'
      - '**/api.yml'

env:
  COMPONENT: api

jobs:
  build-and-push:
    name: Build and push image
    runs-on: ubuntu-latest

    strategy:
      matrix:
        architecture:
          - amd64
          - arm64

    # Cancel in-progress jobs if matching component and platform when new PR arrives.
    concurrency:
      group: containers-api-${{ matrix.architecture }}
      cancel-in-progress: true

    steps:
    - name: Checkout repo
      uses: actions/checkout@v4

    - name: Set up QEMU
      if: matrix.architecture != 'amd64'
      uses: docker/setup-qemu-action@v3
      
    - name: Setup Docker buildx
      uses: docker/setup-buildx-action@v3
      # with:
      #   buildkitd-flags: --debug

    - name: Login to Docker Hub Container Registry
      uses: docker/login-action@v3
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        # logout: false

    - name: Build and push Docker image
      uses: docker/build-push-action@v6
      with:
        context: ./${{ env.COMPONENT }}
        push: true
        cache-from: type=gha,scope=${{ matrix.architecture }}
        cache-to: type=gha,mode=max,scope=${{ matrix.architecture }}
        tags: ${{ secrets.DOCKERHUB_USERNAME }}/hamframe-${{ env.COMPONENT}}:latest
